- name: prepare for buildbot
  hosts: [ master, slaves ]
  sudo: yes
  tasks:
    - user: home={{ home }} name=buildbot state=present system=yes
    - apt: name={{ item }} state=latest
      with_items:
        - python-dev
        - python-pip
        - python-virtualenv
        - git

- name: extra preparation for buildbot slave
  hosts: slaves
  sudo: yes
  tasks:
    - copy: src=sudoers-buildbot dest=/etc/sudoers.d owner=0
    - apt: name={{ item }} state=latest
      with_items:
        - reprepro
        - cowbuilder
        - debootstrap
        - devscripts
        - git-buildpackage
        - debhelper

- name: buildbot slave setup
  hosts: slaves
  sudo: yes
  sudo_user: buildbot
  tasks:
    - pip: name={{ item }} virtualenv={{ venv }}
      with_items:
        - buildbot-slave
    - template: src=virtualenv_exec.j2 dest={{ venv }}/exec mode=755
    - command: "{{ venv }}/exec buildslave create-slave {{ home }}/{{ item }} {{ groups['master'][0] }}:9989
                {{ item }} mebuildslotsaros"
      with_items:
        - rosbuilder1
        - rosbuilder2
    - command: "{{ venv }}/exec buildslave start {{ home }}/{{ item }}"
      with_items:
        - rosbuilder1
        - rosbuilder2

- name: buildbot master setup
  hosts: master
  sudo: yes
  sudo_user: buildbot
  tasks:
    - pip: name={{ item }} virtualenv={{ venv }}
      with_items:
        - rosdistro
        - buildbot
    - template: src=virtualenv_exec.j2 dest={{ venv }}/exec mode=755
    - git: repo={{ buildbot_ros_repo }} dest=~/buildbot-ros
    - command: "{{ venv }}/exec buildbot create-master {{ home }}/buildbot-ros
                 creates={{ home }}/buildbot-ros/buildbot.tac"
    - lineinfile: dest={{ home }}/buildbot-ros/buildbot.tac regexp=^umask line="umask = 0023"
    - file: name={{ home }}/building state=directory mode=755
    - file: name={{ home }}/building/conf state=directory
    - template: src=distributions.j2 dest={{ home }}/building/conf/distributions
    - command: "{{ venv }}/exec buildbot start {{ home }}/buildbot-ros"

